version: '3'

services:
  typescript-plane-boilerplate-db:
    build: ./db
    platform: linux/amd64
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: maindb

  openapi:
    image: openapitools/openapi-generator-cli:v7.2.0
    volumes:
      - ./packages:/work
    command: |
      generate -i
      /work/backend/swagger.json
      --generator-name typescript-fetch
      --input-spec /work/backend/swagger.json
      --output /work/k6/src/generated
      --additional-properties=typescriptThreePlus=true
      --skip-validate-spec